### ISSUE TITLE
Why diff extension can not be installed successfully?

### ISSUE THREAD

**Issue by Kirby13740** [JiangWenPL/FisherRF#22]
![fa9f6d949869d56105ac1f02217e2fe1](https://github.com/user-attachments/assets/79e844e5-4b06-4866-aeb4-7758db45b2de)

**Comment by JiangWenPL** [comment]
Hi Can you put out more error message so that we can help you?

**Comment by Mainak-learner** [comment]
I'm getting the same error message during installations of submodules and diff extension. 

For me, the `CUDA_HOME` env variable is showing as not set even when I'm explicitly setting `CUDA_HOME` using `export` before running the installations.

**Comment by JiangWenPL** [comment]
Did you find similar issues when compiling the official extensions of 3DGS? We did not introduce new dependencies in our CUDA extensions.

**Comment by Mainak-learner** [comment]
Hello,

The error I was getting previously was caused by an incorrect setup of my CUDA environment. 

However, recently, I had been getting an error with the installation of the _simple-knn submodule_.

After some investigation, I found out this was happening because the _simple-knn submodule_ points towards an older commit (**44f7642**). Installing files from this older commit gives rise to a few PyTorch datatype depreciation issues, which cause the installation to fail.

A change should be made that points to the newer commit (86710c2).

**Comment by maxiang0305** [comment]
I miss the same error, the details are as follows:
`Obtaining` file:///home/mx/FM/FisherRF/diff
  Preparing metadata (setup.py) ... done
Installing collected packages: modified_diff_gaussian_rasterization
  DEPRECATION: Legacy editable install of modified_diff_gaussian_rasterization==0.0.0 from file:///home/mx/FM/FisherRF/diff (setup.py develop) is deprecated. pip 25.3 will enforce this behaviour change. A possible replacement is to add a pyproject.toml or enable --use-pep517, and use setuptools >= 64. If the resulting installation is not behaving as expected, try using --config-settings editable_mode=compat. Please consult the setuptools documentation for more information. Discussion can be found at https://github.com/pypa/pip/issues/11457
  Running setup.py develop for modified_diff_gaussian_rasterization
    error: subprocess-exited-with-error
    
    × python setup.py develop did not run successfully.
    │ exit code: 1
    ╰─> [80 lines of output]
        running develop
        /home/mx/anaconda3/envs/FM/lib/python3.10/site-packages/setuptools/_distutils/cmd.py:90: DevelopDeprecationWarning: develop command is deprecated.
        !!
        
                ********************************************************************************
                Please avoid running ``setup.py`` and ``develop``.
                Instead, use standards-based tools like pip or uv.
        
                By 2025-Oct-31, you need to update your project and remove deprecated calls
                or your builds will no longer be supported.
        
                See https://github.com/pypa/setuptools/issues/917 for details.
                ********************************************************************************
        
        !!
          self.initialize_options()
        Obtaining file:///home/mx/FM/FisherRF/diff
          Installing build dependencies: started
          Installing build dependencies: finished with status 'done'
          Checking if build backend supports build_editable: started
          Checking if build backend supports build_editable: finished with status 'done'
          Getting requirements to build editable: started
          Getting requirements to build editable: finished with status 'error'
          error: subprocess-exited-with-error
        
          × Getting requirements to build editable did not run successfully.
          │ exit code: 1
          ╰─> [20 lines of output]
              Traceback (most recent call last):
                File "/home/mx/anaconda3/envs/FM/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 389, in <module>
                  main()
                File "/home/mx/anaconda3/envs/FM/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 373, in main
                  json_out["return_val"] = hook(**hook_input["kwargs"])
                File "/home/mx/anaconda3/envs/FM/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 157, in get_requires_for_build_editable
                  return hook(config_settings)
                File "/tmp/pip-build-env-fnqvhuq_/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 473, in get_requires_for_build_editable
                  return self.get_requires_for_build_wheel(config_settings)
                File "/tmp/pip-build-env-fnqvhuq_/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 331, in get_requires_for_build_wheel
                  return self._get_build_requires(config_settings, requirements=[])
                File "/tmp/pip-build-env-fnqvhuq_/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 301, in _get_build_requires
                  self.run_setup()
                File "/tmp/pip-build-env-fnqvhuq_/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 512, in run_setup
                  super().run_setup(setup_script=setup_script)
                File "/tmp/pip-build-env-fnqvhuq_/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 317, in run_setup
                  exec(code, locals())
                File "<string>", line 67, in <module>
                File "<string>", line 40, in get_extensions
              ModuleNotFoundError: No module named 'torch'
              [end of output]
        
          note: This error originates from a subprocess, and is likely not a problem with pip.
        error: subprocess-exited-with-error
        
        × Getting requirements to build editable did not run successfully.
        │ exit code: 1
        ╰─> See above for output.
        
        note: This error originates from a subprocess, and is likely not a problem with pip.
        Traceback (most recent call last):
          File "<string>", line 2, in <module>
          File "<pip-setuptools-caller>", line 35, in <module>
          File "/home/mx/FM/FisherRF/diff/setup.py", line 64, in <module>
            setup(
          File "/home/mx/anaconda3/envs/FM/lib/python3.10/site-packages/setuptools/__init__.py", line 117, in setup
            return distutils.core.setup(**attrs)
          File "/home/mx/anaconda3/envs/FM/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 186, in setup
            return run_commands(dist)
          File "/home/mx/anaconda3/envs/FM/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 202, in run_commands
            dist.run_commands()
          File "/home/mx/anaconda3/envs/FM/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 1002, in run_commands
            self.run_command(cmd)
          File "/home/mx/anaconda3/envs/FM/lib/python3.10/site-packages/setuptools/dist.py", line 1104, in run_command
            super().run_command(command)
          File "/home/mx/anaconda3/envs/FM/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 1021, in run_command
            cmd_obj.run()
          File "/home/mx/anaconda3/envs/FM/lib/python3.10/site-packages/setuptools/command/develop.py", line 39, in run
            subprocess.check_call(cmd)
          File "/home/mx/anaconda3/envs/FM/lib/python3.10/subprocess.py", line 369, in check_call
            raise CalledProcessError(retcode, cmd)
        subprocess.CalledProcessError: Command '['/home/mx/anaconda3/envs/FM/bin/python3.10', '-m', 'pip', 'install', '-e', '.', '--use-pep517', '--no-deps']' returned non-zero exit status 1.
        [end of output]
    
    note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× python setup.py develop did not run successfully.
│ exit code: 1
╰─> [80 lines of output]
    running develop
    /home/mx/anaconda3/envs/FM/lib/python3.10/site-packages/setuptools/_distutils/cmd.py:90: DevelopDeprecationWarning: develop command is deprecated.
    !!
    
            ********************************************************************************
            Please avoid running ``setup.py`` and ``develop``.
            Instead, use standards-based tools like pip or uv.
    
            By 2025-Oct-31, you need to update your project and remove deprecated calls
            or your builds will no longer be supported.
    
            See https://github.com/pypa/setuptools/issues/917 for details.
            ********************************************************************************
    
    !!
      self.initialize_options()
    Obtaining file:///home/mx/FM/FisherRF/diff
      Installing build dependencies: started
      Installing build dependencies: finished with status 'done'
      Checking if build backend supports build_editable: started
      Checking if build backend supports build_editable: finished with status 'done'
      Getting requirements to build editable: started
      Getting requirements to build editable: finished with status 'error'
      error: subprocess-exited-with-error
    
      × Getting requirements to build editable did not run successfully.
      │ exit code: 1
      ╰─> [20 lines of output]
          Traceback (most recent call last):
            File "/home/mx/anaconda3/envs/FM/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 389, in <module>
              main()
            File "/home/mx/anaconda3/envs/FM/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 373, in main
              json_out["return_val"] = hook(**hook_input["kwargs"])
            File "/home/mx/anaconda3/envs/FM/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 157, in get_requires_for_build_editable
              return hook(config_settings)
            File "/tmp/pip-build-env-fnqvhuq_/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 473, in get_requires_for_build_editable
              return self.get_requires_for_build_wheel(config_settings)
            File "/tmp/pip-build-env-fnqvhuq_/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 331, in get_requires_for_build_wheel
              return self._get_build_requires(config_settings, requirements=[])
            File "/tmp/pip-build-env-fnqvhuq_/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 301, in _get_build_requires
              self.run_setup()
            File "/tmp/pip-build-env-fnqvhuq_/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 512, in run_setup
              super().run_setup(setup_script=setup_script)
            File "/tmp/pip-build-env-fnqvhuq_/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 317, in run_setup
              exec(code, locals())
            File "<string>", line 67, in <module>
            File "<string>", line 40, in get_extensions
          ModuleNotFoundError: No module named 'torch'
          [end of output]
    
      note: This error originates from a subprocess, and is likely not a problem with pip.
    error: subprocess-exited-with-error
    
    × Getting requirements to build editable did not run successfully.
    │ exit code: 1
    ╰─> See above for output.
    
    note: This error originates from a subprocess, and is likely not a problem with pip.
    Traceback (most recent call last):
      File "<string>", line 2, in <module>
      File "<pip-setuptools-caller>", line 35, in <module>
      File "/home/mx/FM/FisherRF/diff/setup.py", line 64, in <module>
        setup(
      File "/home/mx/anaconda3/envs/FM/lib/python3.10/site-packages/setuptools/__init__.py", line 117, in setup
        return distutils.core.setup(**attrs)
      File "/home/mx/anaconda3/envs/FM/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 186, in setup
        return run_commands(dist)
      File "/home/mx/anaconda3/envs/FM/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 202, in run_commands
        dist.run_commands()
      File "/home/mx/anaconda3/envs/FM/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 1002, in run_commands
        self.run_command(cmd)
      File "/home/mx/anaconda3/envs/FM/lib/python3.10/site-packages/setuptools/dist.py", line 1104, in run_command
        super().run_command(command)
      File "/home/mx/anaconda3/envs/FM/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 1021, in run_command
        cmd_obj.run()
      File "/home/mx/anaconda3/envs/FM/lib/python3.10/site-packages/setuptools/command/develop.py", line 39, in run
        subprocess.check_call(cmd)
      File "/home/mx/anaconda3/envs/FM/lib/python3.10/subprocess.py", line 369, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['/home/mx/anaconda3/envs/FM/bin/python3.10', '-m', 'pip', 'install', '-e', '.', '--use-pep517', '--no-deps']' returned non-zero exit status 1.
    [end of `output]`

**Comment by JiangWenPL** [comment]
It says ` No module named 'torch'`. Can you confirm if you are running `pip` with your designated environment?

**Comment by OceanCam** [comment]
I encountered the same issue, and my solution was to add a `pyproject.toml` file in the `diff` folder with the following content:
```
[build-system]
requires = ["setuptools>=64", "wheel"]
build-backend = "setuptools.build_meta"
```
Then, I ran `pip install -v -e ./diff/ --no-build-isolation`.  
I think this might be related to the build isolation feature in newer versions of `pip`.
